// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace BoundTreeGenerator
{
    internal sealed class BoundNodeClassWriter_CS : BoundNodeClassWriter
    {
        internal BoundNodeClassWriter_CS(TextWriter writer, Tree tree)
            : base(writer, tree, TargetLanguage.CSharp) { }

        protected override void InitializeValueTypes(ref Dictionary<string, bool> _valueTypes)
        {
            _valueTypes.Add("bool", true);
            _valueTypes.Add("int", true);
            _valueTypes.Add("uint", true);
            _valueTypes.Add("short", true);
            _valueTypes.Add("ushort", true);
            _valueTypes.Add("long", true);
            _valueTypes.Add("ulong", true);
            _valueTypes.Add("byte", true);
            _valueTypes.Add("sbyte", true);
            _valueTypes.Add("char", true);
            _valueTypes.Add("Boolean", true);
        }

        protected override void AutoGenerated() => WriteLine("// <auto-generated />");

        protected override void WriteUsing(string nsName) => WriteLine($"using {nsName};");

        protected override void WriteStartNamespace()
        {
            WriteLine("using Microsoft.CodeAnalysis.Text;");
            WriteLine("using Microsoft.CodeAnalysis.CSharp.Symbols;");
            WriteLine("using Microsoft.CodeAnalysis.CSharp.Syntax;");
            Blank();
            WriteLine("namespace Microsoft.CodeAnalysis.CSharp");
            LBrace();
        }

        protected override void End_Namespace() => RBrace();

        protected override void WriteKinds()
        {
            WriteLine("internal enum BoundKind: byte");
            LBrace();
            foreach (var node in _tree.Types.OfType<Node>())
                WriteLine($"{FixKeyword(StripBound(node.Name))},");
            RBrace();
        }

        protected override void WriteClassHeader(TreeType node)
        {
            string abstr = "";
            if (node is AbstractNode)
                abstr = "abstract ";
            else if (CanBeSealed(node))
                abstr = "sealed ";
            WriteLine($"internal {abstr}partial class {node.Name} : {node.Base}");
            LBrace();
        }

        protected override void WriteClassFooter(TreeType node) => RBrace();
        protected override void Or<T>(IEnumerable<T> items, Func<T, string> func) => SeparatedList(" || ", items, func);

        protected override void WriteConstructorWithHasErrors(TreeType node, bool isPublic, bool hasErrorsIsOptional)
        {
            // A public constructor does not have an explicit kind parameter.
            var porp = isPublic ? "public" : "protected";
            Write($"{porp} {node.Name}");
            IEnumerable<string> fields = isPublic ? new[] { "SyntaxNode syntax" } : new[] { "BoundKind kind", "SyntaxNode syntax" };
            fields = fields.Concat(from field in AllSpecifiableFields(node)
                                   select field.Type + " " + ToCamelCase(field.Name));

            if (hasErrorsIsOptional)
                fields = fields.Concat(new[] { "bool hasErrors = false" });
            else
                fields = fields.Concat(new[] { "bool hasErrors" });

            ParenList(fields, x => x);
            Blank();
            Indent();
            Write(": base(");
            if (isPublic)
            {
                // Base call has bound kind, syntax, all fields in base type, plus merged HasErrors.
                Write($"BoundKind.{StripBound(node.Name)}");
                Write(", syntax, ");
                WriteFields("", AllSpecifiableFields(BaseType(node)), node, ", ");
                Or((new[] { "hasErrors" })
                    .Concat(from field in AllNodeOrNodeListFields(node)
                            select ToCamelCase(field.Name) + ".HasErrors()"), x => x);
            }
            else
            {
                // Base call has kind, syntax, and hasErrors. No merging of hasErrors because derived class already did the merge.
                Write("kind, syntax, ");
                WriteFields("", AllSpecifiableFields(BaseType(node)), node, ", ");
                Write("hasErrors");
            }
            Write(")");
            Blank();
            Undent();
            LBrace();

            WriteNullChecks(node);

            foreach (var field in Fields(node))
            {
                var value = FieldNullHandling(node, field.Name) == NullHandling.Always ? "null" : ToCamelCase(field.Name);
                if (IsPropertyOverrides(field))
                {
                    WriteLine($"this._{field.Name} = {value};");
                }
                else
                {
                    WriteLine($"this.{field.Name} = {value};");
                }
            }
            RBrace();
            Blank();
        }

        // This constructor should only be created if no node or list fields, since it just calls base class constructor
        // without merging hasErrors.
        protected override void WriteConstructorWithoutHasErrors(TreeType node, bool isPublic)
        {
            // A public constructor does not have an explicit kind parameter.
            var porp = isPublic ? "public" : "protected";
            Write($"{porp} {node.Name}");
            IEnumerable<string> fields = isPublic ? new[] { "SyntaxNode syntax" } : new[] { "BoundKind kind", "SyntaxNode syntax" };
            fields = fields.Concat(from field in AllSpecifiableFields(node)
                                   select field.Type + " " + ToCamelCase(field.Name));
            ParenList(fields, x => x);
            Blank();
            Indent();
            Write(": base(");
            if (isPublic)
            {
                // Base call has bound kind, syntax, fields.
                Write($"BoundKind.{StripBound(node.Name)}");
                Write(", syntax");
                WriteFields(", ", AllSpecifiableFields(BaseType(node)), node, "");
            }
            else
            {
                // Base call has kind, syntax, fields
                Write("kind, syntax");
                WriteFields(", ", AllSpecifiableFields(BaseType(node)), node, "");
            }
            Write(")");
            Blank();
            Undent();
            LBrace();

            WriteNullChecks(node);

            foreach (var field in Fields(node))
            {
                var value = FieldNullHandling(node, field.Name) == NullHandling.Always ? "null" : ToCamelCase(field.Name);
                if (IsPropertyOverrides(field))
                {
                    WriteLine($"this._{field.Name} = {value};");
                }
                else
                {
                    WriteLine($"this.{field.Name} = {value};");
                }
            }
            RBrace();
            Blank();
        }

        private void WriteFields(string prefix, IEnumerable<Field> fx, TreeType node, string postfix)
        {
            foreach (Field baseField in fx)
            {
                var value = FieldNullHandling(node, baseField.Name) == NullHandling.Always ? "null" : ToCamelCase(baseField.Name);
                Write($"{prefix}{value}{postfix}");
            }
        }

        protected override void Write_DebugAssert_Nulls(bool isROArray, Field field)
        {
            Write("Debug.Assert(");
            var member = ToCamelCase(field.Name);
            if (isROArray)
                Write($"!{member}.IsDefault");
            else
                Write($"{member} != null");

            WriteLine($", \"Field '{member}' cannot be null (use Null=\\\"allow\\\" in BoundNodes.xml to remove this check)\");");
        }

        protected override void WriteField(Field field)
        {
            Blank();
            var newobj = (IsNew(field) ? "new " : "");
            if (IsPropertyOverrides(field))
            {
                WriteLine($"private readonly {field.Type} _{field.Name};");
                WriteLine($"public override {newobj}{field.Type} {field.Name} {{ get {{ return _{field.Name};}} }}");
            }
            else
            {
                WriteLine($"public {newobj}{field.Type} {field.Name} {{ get; }}");
            }
        }

        protected override void WriteAccept(string name)
        {
            //Blank();
            //WriteLine("public override R Accept<A, R>(BoundTreeVisitor<A, R> visitor, A arg)");
            //Brace();
            //WriteLine("return visitor.Visit{0}(this, arg);", StripBound(name));
            //Unbrace();

            Blank();
            WriteLine("public override BoundNode Accept(BoundTreeVisitor visitor)");
            LBrace();
            WriteLine($"return visitor.Visit{StripBound(name)}(this);");
            RBrace();
        }
        protected override void Write_Update(Node node, Boolean emitNew)
        {
            Blank();
            var newobj = emitNew ? " new" : "";
            Write($"public{newobj} {node.Name} Update");
            LParens();
            Comma(AllSpecifiableFields(node), field => $"{field.Type} {ToCamelCase(field.Name)}");
            RParens();
            Blank();
            LBrace();
            if (AllSpecifiableFields(node).Any())
            {
                Write("if ");
                LParens();
                Or(AllSpecifiableFields(node), field => $"{ToCamelCase(field.Name)} != this.{field.Name}");
                RParens();
                Blank();
                LBrace();
                Write($"var result = new {node.Name}");
                var fields = new[] { "this.Syntax" }.Concat(AllSpecifiableFields(node).Select(f => ToCamelCase(f.Name))).Concat(new[] { "this.HasErrors" });
                ParenList(fields);
                WriteLine(";");
                WriteLine("result.WasCompilerGenerated = this.WasCompilerGenerated;");
                WriteLine("return result;");
                RBrace();
            }
            WriteLine("return this;");
            RBrace();
        }

        protected override void WriteVisitor()
        {
            Blank();
            WriteLine("internal abstract partial class BoundTreeVisitor<A,R>");
            LBrace();

            Blank();
            WriteLine("[MethodImpl(MethodImplOptions.NoInlining)]");
            WriteLine("internal R VisitInternal(BoundNode node, A arg)");
            LBrace();
            WriteLine("switch (node.Kind)");
            LBrace();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                var strip = StripBound(node.Name);
                WriteLine($"case BoundKind.{FixKeyword(strip)}: ");
                Indent();
                WriteLine($"return Visit{strip}(node as {node.Name}, arg);");
                Undent();
            }
            RBrace();
            Blank(); // end switch
            WriteLine("return default(R);");
            RBrace(); // end method
            RBrace(); // end class

            //Blank();
            //WriteLine("internal abstract partial class BoundTreeVisitor");
            //Brace();

            //Blank();
            //WriteLine("[MethodImpl(MethodImplOptions.NoInlining)]");
            //WriteLine("internal BoundNode VisitInternal(BoundNode node)");
            //Brace();
            //WriteLine("switch (node.Kind)");
            //Brace();
            //foreach (var node in tree.Types.OfType<Node>())
            //{
            //    WriteLine("case BoundKind.{0}: ", FixKeyword(StripBound(node.Name)));
            //    Indent();
            //    WriteLine("return Visit{0}(node as {1});", StripBound(node.Name), node.Name);
            //    Outdent();
            //}
            //Unbrace(); // end switch
            //Blank();
            //WriteLine("return null;");
            //Unbrace(); // end method
            //Unbrace(); // end class

            Blank();
            WriteLine("internal abstract partial class BoundTreeVisitor<A,R>");
            LBrace();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                WriteLine($"public virtual R Visit{StripBound(node.Name)}({node.Name} node, A arg)");
                LBrace();
                WriteLine("return this.DefaultVisit(node, arg);");
                RBrace();
            }
            RBrace();

            Blank();
            WriteLine("internal abstract partial class BoundTreeVisitor");
            LBrace();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                WriteLine($"public virtual BoundNode Visit{StripBound(node.Name)}({node.Name} node)");
                LBrace();
                WriteLine("return this.DefaultVisit(node);");
                RBrace();
            }
            RBrace();
        }

        protected override void WriteWalker()
        {
            Blank();
            WriteLine("internal abstract partial class BoundTreeWalker : BoundTreeVisitor");
            LBrace();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                WriteLine($"public override BoundNode Visit{StripBound(node.Name)}({node.Name} node)");
                LBrace();
                foreach (Field field in AllFields(node).Where(f => IsDerivedOrListOfDerived("BoundNode", f.Type) && !SkipInVisitor(f)))
                {
                    var member = IsNodeList(field.Type) ? "List" : "";
                    WriteLine($"this.Visit{member}(node.{field.Name});");
                }
                WriteLine("return null;");
                RBrace();
            }
            RBrace();
        }

        protected override void WriteTreeDumperNodeProducer()
        {
            Blank();
            WriteLine("internal sealed class BoundTreeDumperNodeProducer : BoundTreeVisitor<object, TreeDumperNode>");
            LBrace();
            WriteLine("private BoundTreeDumperNodeProducer()");
            LBrace();
            RBrace();
            WriteLine("public static TreeDumperNode MakeTree(BoundNode node)");
            LBrace();
            WriteLine("return (new BoundTreeDumperNodeProducer()).Visit(node, null);");
            RBrace();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                var strip = StripBound(node.Name);
                WriteLine($"public override TreeDumperNode Visit{strip}({node.Name} node, object arg)");
                LBrace();
                Write($"return new TreeDumperNode(\"{ToCamelCase(strip)}\", null, ");
                var allFields = AllFields(node).ToArray();
                if (allFields.Length > 0)
                {
                    WriteLine("new TreeDumperNode[]");
                    LBrace();
                    for (int i = 0; i < allFields.Length; ++i)
                    {
                        Field field = allFields[i];
                        Write($"new TreeDumperNode(\"{ToCamelCase(field.Name)}\", ");
                        if (IsDerivedType("BoundNode", field.Type))
                            Write($"null, new TreeDumperNode[] {{ Visit(node.{field.Name}, null) }})");
                        else if (IsListOfDerived("BoundNode", field.Type))
                        {
                            if (IsImmutableArray(field.Type) && FieldNullHandling(node, field.Name) == NullHandling.Disallow)
                            {
                                Write($"null, from x in node.{field.Name} select Visit(x, null))");
                            }
                            else
                            {
                                Write($"null, node.{field.Name}.IsDefault ? Array.Empty<TreeDumperNode>() : from x in node.{field.Name} select Visit(x, null))");
                            }
                        }
                        else
                            Write($"node.{ field.Name}, null)");

                        if (i == allFields.Length - 1)
                            WriteLine("");
                        else
                            WriteLine(",");
                    }
                    RBrace();
                }
                else
                {
                    WriteLine("Array.Empty<TreeDumperNode>()");
                }
                WriteLine(");");
                RBrace();
            }
            RBrace();
        }

        protected override void WriteRewriter()
        {
            Blank();
            WriteLine("internal abstract partial class BoundTreeRewriter : BoundTreeVisitor");
            LBrace();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                WriteLine($"public override BoundNode Visit{StripBound(node.Name)}({node.Name} node)");
                LBrace();
                bool hadField = false;
                foreach (Field field in AllNodeOrNodeListFields(node))
                {
                    var camel = ToCamelCase(field.Name);
                    hadField = true;
                    if (SkipInVisitor(field))
                    {
                        WriteLine($"{field.Type} {camel} = node.{field.Name};");
                    }
                    else
                    {
                        var member = IsNodeList(field.Type) ? "List" : "";
                        WriteLine($"{field.Type} {camel} = ({field.Type})this.Visit{member}(node.{field.Name});");
                    }
                }
                foreach (Field field in AllTypeFields(node))
                {
                    hadField = true;
                    WriteLine($"TypeSymbol {ToCamelCase(field.Name)} = this.VisitType(node.{field.Name});");
                }
                if (hadField)
                {
                    Write("return node.Update");
                    ParenList(AllSpecifiableFields(node), field => IsDerivedOrListOfDerived("BoundNode", field.Type) || field.Type == "TypeSymbol" ? ToCamelCase(field.Name) : $"node.{field.Name}");
                    WriteLine(";");
                }
                else
                {
                    WriteLine("return node;");
                }

                RBrace();
            }
            RBrace();
        }

        protected override bool IsImmutableArray(string typeName) => typeName.StartsWith("ImmutableArray<", StringComparison.Ordinal);

        protected override bool IsNodeList(string typeName) => typeName.StartsWith("IList<", StringComparison.Ordinal) ||
                                                               typeName.StartsWith("ImmutableArray<", StringComparison.Ordinal);

        protected override string GetGenericType(string typeName)
        {
            if (!typeName.Contains("<")) return typeName;
            int iStart = typeName.IndexOf('<');
            return typeName.Substring(0, iStart);
        }

        protected override string GetElementType(string typeName)
        {
            if (!typeName.Contains("<")) return string.Empty;
            int iStart = typeName.IndexOf('<');
            int iEnd = typeName.IndexOf('>', iStart + 1);
            if (iEnd < iStart) return string.Empty;
            return typeName.Substring(iStart + 1, iEnd - iStart - 1);
        }

        protected override string EscapeKeyword(string name) => "@" + name;

        protected override bool IsKeyword(string name)
        {
            switch (name)
            {
                case "bool":
                case "byte":
                case "sbyte":
                case "short":
                case "ushort":
                case "int":
                case "uint":
                case "long":
                case "ulong":
                case "double":
                case "float":
                case "decimal":
                case "string":
                case "char":
                case "object":
                case "typeof":
                case "sizeof":
                case "null":
                case "true":
                case "false":
                case "if":
                case "else":
                case "while":
                case "for":
                case "foreach":
                case "do":
                case "switch":
                case "case":
                case "default":
                case "lock":
                case "try":
                case "throw":
                case "catch":
                case "finally":
                case "goto":
                case "break":
                case "continue":
                case "return":
                case "public":
                case "private":
                case "internal":
                case "protected":
                case "static":
                case "readonly":
                case "sealed":
                case "const":
                case "new":
                case "override":
                case "abstract":
                case "virtual":
                case "partial":
                case "ref":
                case "out":
                case "in":
                case "where":
                case "params":
                case "this":
                case "base":
                case "namespace":
                case "using":
                case "class":
                case "struct":
                case "interface":
                case "delegate":
                case "checked":
                case "get":
                case "set":
                case "add":
                case "remove":
                case "operator":
                case "implicit":
                case "explicit":
                case "fixed":
                case "extern":
                case "event":
                case "enum":
                case "unsafe":
                    return true;
                default:
                    return false;
            }
        }
    }
}
