// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Roslyn.Compilers.Internal.BoundTreeGenerator
{
    internal abstract partial class BoundNodeClassWriter
    {
        protected Action EOL() => () => _o.EOL();
        internal static void Write(TextWriter writer, Tree tree, TargetLanguage targetLang)
        {
            switch (targetLang)
            {
                case TargetLanguage.CSharp: new BoundNodeClassWriter_CS(writer, tree).WriteFile(); break;
                case TargetLanguage.VB: new BoundNodeClassWriter_VB(writer, tree).WriteFile(); break;
                default: throw new UnexpectedTargetLanguage(nameof(_targetLang));
            }
        }

        protected void WriteFile()
        {
                try
            {
                AutoGenerated();
                _o.Blank();
                CommonImports();
                _o.Blank();
                LanguageSpecificImportedNamespaces();
                _o.Blank();
                InsideNamespace(
                    Lang.InsideNamespace(), _o,
                () => Write_Kinds_Enum(),
                () => WriteTypes(),
                () => WriteVisitor(),
                () => WriteWalker(),
                () => WriteRewriter(),
                () => WriteTreeDumperNodeProducer()
               );
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                throw new Exception("Rethrowing Exception", e);
            }
            finally
            {
                _o.Dispose();
            }
        }

        protected Dictionary<string, bool> _valueTypes;
        protected readonly TargetLanguage _targetLang;
        protected readonly Dictionary<string, string> _typeMap;
        protected readonly IndentedWriter _o;
        protected readonly Tree _tree;
        public    readonly LangSpecific Lang;

        internal BoundNodeClassWriter(Tree tree, TargetLanguage targetLang, IndentedWriter indenter, LangSpecific lang)
        {
            _tree = tree ?? throw new ArgumentNullException(nameof(tree));
            _o = indenter ?? throw new ArgumentNullException(nameof(indenter));
            _typeMap = tree.Types.Where(t => !(t is EnumType || t is ValueType)).ToDictionary(n => n.Name, n => n.Base);
            _typeMap.Add(tree.Root, null);
            _targetLang = targetLang;
            Lang = lang ?? throw new ArgumentNullException(nameof(Lang));
            _o.Lang = Lang;
            _o.Lang._iw = _o;
            InitializeValueTypes();
        }

        public bool IsNodeOrNodeList(string typeName) => IsNode(typeName) || IsNodeList(typeName);

        protected TreeType BaseType(TreeType node) => (_typeMap[node.Name] != _tree.Root) ? (_tree.Types.Single(t => t.Name == _typeMap[node.Name])) : null;

        protected NullHandling FieldNullHandling(TreeType node, string fieldName)
        {
            var f = GetField(node, fieldName);

            if (f.Null != null)
            {
                switch (f.Null.ToUpperInvariant())
                {
                    case "ALLOW": return NullHandling.Allow;
                    case "DISALLOW": return NullHandling.Disallow;
                    case "ALWAYS": return NullHandling.Always;
                    case "NOTAPPLICABLE": return NullHandling.NotApplicable;
                    case "": break;
                    default: throw new ArgumentException("Unexpected value", nameof(f.Null));
                }
            }

            if (f.Override)
                return FieldNullHandling(BaseType(node), fieldName);
            else if (!IsValueType(f.Type) || GetGenericType(f.Type) == "ImmutableArray")
                return NullHandling.Disallow; // default is to disallow nulls.
            else
                return NullHandling.NotApplicable;   // value types can't check nulls.
        }

        protected Field GetField(TreeType node, string fieldName)
        {
            var fieldsWithName = from f in FieldsIncludingOverrides(node) where f.Name == fieldName select f;
            if (fieldsWithName.Any())
                return fieldsWithName.Single();
            else if (BaseType(node) != null)
                return GetField(BaseType(node), fieldName);
            else
                throw new InvalidOperationException($"Field {fieldName} not found in type {node.Name}");
        }

        protected void InitializeValueTypes()
        {
            _valueTypes = new Dictionary<string, bool>();
            foreach (ValueType t in _tree.Types.Where(t => t is ValueType))
                _valueTypes.Add(t.Name, true);
            InitializeValueTypes(ref _valueTypes);

            _valueTypes.Add("Int8", true);
            _valueTypes.Add("Int16", true);
            _valueTypes.Add("Int32", true);
            _valueTypes.Add("Int64", true);
            _valueTypes.Add("UInt8", true);
            _valueTypes.Add("UInt16", true);
            _valueTypes.Add("UInt32", true);
            _valueTypes.Add("UInt64", true);
            _valueTypes.Add("ImmutableArray", true);
            _valueTypes.Add("PropertyAccessKind", true);
        }

        protected void Write_Modifier(string text) => $"{text} ".Output(_o)();

        #region "Statement Handling"
        protected Action Return(string text, bool eol) => ()=> $"{Lang.@return()} {text}".Code(_o,eol);
        protected void Comment(string commentText) => $"{Lang.CommentMarker()} {commentText}".Output(_o, true)();

        protected void AutoGenerated() => Comment(XMLNode("auto-generated"));

        #region "Imports and Namespace"

        protected void NamespaceImports(params string[] namespaces) => namespaces.ForAll(null, (ns,eolLast)=>Lang.ImportNamespace(ns, _o, true))();

        protected void LanguageSpecificImportedNamespaces() => NamespaceImports(Lang.ImportedNamespaces().ToArray());

        private void CommonImports()
        {
            NamespaceImports(
              "System", "System.Collections", "System.Collections.Generic", "System.Collections.Immutable",
              "System.Diagnostics", "System.Linq", "System.Runtime.CompilerServices", "System.Threading", "System.Text",
              "Microsoft.CodeAnalysis.Collections", "Roslyn.Utilities");
        }

        protected virtual void InsideNamespace(string ns, IndentedWriter iw,params Action[] bodylines)
        {
            $"{Lang.Namespace()} {ns}".Output(iw).WithBody(
            bodylines.ForAll(null,(bodyline,__)=> bodyline?.Indented(iw)()),
            Lang.End_Namespace.Output(iw))();
        }
        #endregion
        #endregion

        protected string XMLNode(string name) => $"< {name} />";
  
        protected void WriteTypes()
        {
            foreach(var node in _tree.Types.Where(n => !(n is PredefinedNode)))
                 WriteType(node);
            _o.Blank();
        }

        protected string[] Parameters(params string[] parameters) => parameters;

        protected bool CanBeSealed(TreeType node) => !_typeMap.Values.Contains(node.Name);  // Is this type the base type of anything?
        protected string OutIsPublic(bool isPublic) => isPublic ? Lang.@public() : Lang.@protected();

        #region "Parens"

        private  Func<string> SeparatedList<T>(string separator, IEnumerable<T> items, Func<T, string> func)
        {
            if (separator == null) throw new ArgumentNullException(nameof(separator));
            if (items == null)     throw new ArgumentNullException(nameof(items));
            if (func == null)      throw new ArgumentNullException(nameof(func));

            return () =>
            {
                var res = "";
                var isFirst = true;
                foreach (var item in items)
                {
                    if (!isFirst) res += separator;
                    isFirst = false;
                    res += func(item);
                }
                return res;
            };
        }

        protected Func<string> Or<T>(IEnumerable<T> items, Func<T, string> func)  => SeparatedList($" {Lang.OrElse()} ", items, func);

        protected Func<string> AndAlso<T>(IEnumerable<T> items, Func<T, string> func) => SeparatedList($" {Lang.AndAlso()} ", items, func);

        protected void ParenList(IEnumerable<string> items)
        {
            if (items == null) items = new String[] { }; // throw new ArgumentNullException(nameof(items));
            ParenList(items, x => x);
        }

        protected void ParenList<T>(IEnumerable<T> items, Func<T, string> func)
        {
            if (items == null)throw new ArgumentNullException(nameof(items));
            if (func == null) throw new ArgumentNullException(nameof(func));
            InParens(SeparatedList(", ",items, func).Output(_o))();
        }

        protected Action InParens(Action act, bool eol = false)
            => $"(".Output(_o).WithBody(act, ")".Output(_o, eol));

        #endregion

        #region "Parameter"
        protected string Parameter(string name, string typeName) => Lang.NameAsType(name.ToCamelCase(this.Lang), typeName);

        protected IEnumerable<string> OutputFirstParameters(bool isPublic)
        {
            if (!isPublic) yield return Lang.NameAsType("kind", "BoundKind");
            yield return Lang.NameAsType("syntax", "SyntaxNode");
        }
        #endregion

    }
}
