// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace BoundTreeGenerator
{
    internal sealed class BoundNodeClassWriter_VB : BoundNodeClassWriter
    {
        internal BoundNodeClassWriter_VB(TextWriter writer, Tree tree) : base(writer, tree, TargetLanguage.VB) { }
        #region "helpers: End"
        private void EOL() => WriteLine("");
        private void Write_End(string text, bool afterBlankLine = false, bool thenBlankLine = false) => WriteLine($"End {text}", undent: true, thenBlankLine: thenBlankLine, afterBlankLine: afterBlankLine);
        private void End_Sub() => Write_End("Sub", thenBlankLine: true);
        private void End_Enum() => Write_End("Enum", thenBlankLine: true);
        private void End_Select() => Write_End("Select");
        private void End_Class(bool thenBlankLine = true) => Write_End("Class", thenBlankLine: thenBlankLine);
        private void End_Function(bool thenBlankLine = true) => Write_End("Function", thenBlankLine: thenBlankLine);
        protected override void End_Namespace() => Write_End("Namespace");
        #endregion

        private void ReturnNode() => Return("node", eol: false);
        private void Friend_MustInherit_Partial_Class(string className, string inherits = null) => Write_Class("Friend MustInherit Partial ", className, inherits);
        private void Write_Class(string modifiers, string className, string inherits) => WriteLine($"{modifiers}Class {className}{(inherits == null ? "" : $" : Inherits {inherits}")}", thenIndent: true, thenBlankLine: true);

        private void WriteArgumentsToMethod(string prefix, IEnumerable<Field> fx, TreeType node, string postfix)
        {
            foreach (var baseField in fx)
            {
                var value = FieldNullHandling(node, baseField.Name) == NullHandling.Always ? "Nothing" : ToCamelCase(baseField.Name);
                Write($"{prefix}{value}{postfix}");
            }
        }

        private void Return(string text, bool eol = true) { if (eol) { WriteLine($"Return {text}"); } else { Write($"Return {text}"); } }
        private string NameOf(string name) => $"{{NameOf({name})}}";

        #region "protected override void"
        protected override void InitializeValueTypes(ref Dictionary<string, bool> _valueTypes)
        {
            _valueTypes.Add("Boolean", true);
            _valueTypes.Add("Integer", true);
            _valueTypes.Add("UInteger", true);
            _valueTypes.Add("Short", true);
            _valueTypes.Add("UShort", true);
            _valueTypes.Add("Long", true);
            _valueTypes.Add("ULong", true);
            _valueTypes.Add("Byte", true);
            _valueTypes.Add("SByte", true);
            _valueTypes.Add("Char", true);
        }
        protected override void AutoGenerated() => WriteLine("' <auto-generated />");
        protected override void WriteUsing(string nsName) => WriteLine($"Imports {nsName}");
        protected override void WriteStartNamespace()
        {
            WriteLine("Imports Microsoft.CodeAnalysis.Text");
            WriteLine("Imports Microsoft.CodeAnalysis.VisualBasic.Symbols");
            WriteLine("Imports Microsoft.CodeAnalysis.VisualBasic.Syntax");
            WriteLine("Namespace Microsoft.CodeAnalysis.VisualBasic", thenIndent: true, afterBlankLine: true);
        }
        protected override void WriteKinds()
        {
            WriteLine("Friend Enum BoundKind as Byte", thenIndent: true, afterBlankLine: true);
            foreach (var node in _tree.Types.OfType<Node>())
                WriteLine(FixKeyword(StripBound(node.Name)));
            End_Enum();
        }
        protected override void WriteClassHeader(TreeType node)
        {
            var abstr = "";
            if (node is AbstractNode)
                abstr = "MustInherit ";
            else if (CanBeSealed(node))
                abstr = "NotInheritable ";
            Write_Class($"Friend {abstr}Partial ", node.Name, node.Base);
        }
        protected override void WriteClassFooter(TreeType node) => End_Class(thenBlankLine: false);
        protected override void Or<T>(IEnumerable<T> items, Func<T, string> func) => SeparatedList(" OrElse ", items, func);
        private void AndAlso<T>(IEnumerable<T> items, Func<T, string> func) => SeparatedList(" AndAlso ", items, func);

        private string OutIsPublic(bool isPublic) => isPublic ? "Public" : "Protected";
        private void WriteSubNew(bool isPublic) => Write($"{OutIsPublic(isPublic)} Sub New");
        private void SubMewParameters(TreeType node, bool isPublic, bool? hasErrorsIsOptional = default)
        {
            var fields = OutputFirstParameters(isPublic).Concat(from field in AllSpecifiableFields(node) select NameAsType(field.Name, field.Type));
            if (hasErrorsIsOptional.HasValue) { Include_HasError(); };
            ParenList(fields, x => x);
            Blank();
            Indent();

            void Include_HasError()
            {
                var param = NameAsType("hasErrors", "Boolean");
                if (hasErrorsIsOptional.Value)
                    fields = fields.Concat(new[] { $"Optional {param} = False" });
                else
                    fields = fields.Concat(new[] { param });
            }
        }

        protected override void WriteConstructorWithHasErrors(TreeType node, bool isPublic, bool hasErrorsIsOptional)
        {
            // A public constructor does not have an explicit kind parameter.
            WriteSubNew(isPublic);
            SubMewParameters(node, isPublic, hasErrorsIsOptional);
            Write("MyBase.New(");
            if (isPublic) { IsPublic(); }  else  { NonPublic(); }
            RParens();
            EOL();
            WriteNullChecks(node);
            foreach (var field in Fields(node))
            {
                var value = FieldNullHandling(node, field.Name) == NullHandling.Always ? "Nothing" : ToCamelCase(field.Name);
                WriteLine($"_{field.Name} = {value}");
            }

            var hasValidate = HasValidate(node);

            if (hasValidate) WriteLine("Validate()");

            End_Sub();

            IfHasValidateThenWrite_ValidateMethod();

            void IfHasValidateThenWrite_ValidateMethod()
            {
                if (!hasValidate) return;
                WriteLine("Private Partial Sub Validate()",thenIndent:true);
                End_Sub();
            }
            void IsPublic()
            {
                // Base call has bound kind, syntax, all fields in base type, plus merged HasErrors.
                Write($"BoundKind.{StripBound(node.Name)}");
                Write(", syntax, ");
                WriteArgumentsToMethod("", AllSpecifiableFields(BaseType(node)), node, ", ");

                Or((new[] { "hasErrors" })
                    .Concat(from field in AllNodeOrNodeListFields(node)
                            select ToCamelCase(field.Name) + ".NonNullAndHasErrors()"), x => x);
            }
            void NonPublic()
            {           
                // Base call has kind, syntax, and hasErrors. No merging of hasErrors because derived class already did the merge.
                Write("kind, syntax, ");
                WriteArgumentsToMethod("", AllSpecifiableFields(BaseType(node)), node, ", ");
                Write("hasErrors");
            }
        }
        protected override void Write_DebugAssert_Nulls(bool isROArray, Field field)
        {
            var fieldName = ToCamelCase(field.Name);
            Write("Debug.Assert(");
            if (isROArray) { Write($"Not {fieldName}.IsDefault"); } else { Write($"{fieldName} IsNot Nothing"); }
            WriteLine($", $\"Field '{NameOf(fieldName)}' cannot be null (use Null=\"\"allow\"\" in BoundNodes.xml to remove this check)\")");
        }

        protected override void WriteField(Field field)
        {
            var shadows = IsNew(field) ? "Shadows " : (IsPropertyOverrides(field) ? "Overrides " : "");
            Write($"Public {shadows}ReadOnly Property ");
            WriteLine(NameAsType(field.Name, field.Type));
        }

        private void MyBase() => Write("MyBase.New");
        // This constructor should only be created if no node or list fields, since it just calls base class constructor
        // without merging hasErrors.
        protected override void WriteConstructorWithoutHasErrors(TreeType node, bool isPublic)
        {
            WriteSubNew(isPublic);
            SubMewParameters(node, isPublic);
            MyBase();
            LParens();
            if (isPublic) { WriteBaseCall_ForBoundKindSyntaxFields(); } else { WriteBaseCall_ForKindSyntaxFields(); }
            WriteLine(")");
            WriteNullChecks(node);

            foreach (var field in Fields(node))
            {
                var value = FieldNullHandling(node, field.Name) == NullHandling.Always ? "Nothing" : ToCamelCase(field.Name);
                WriteLine($"_{field.Name} = {value}");
            }

            if (HasValidate(node)) WriteLine("Validate()");

            End_Sub();
            void WriteBaseCall_ForBoundKindSyntaxFields()
            {
                // Base call has bound kind, syntax, fields.
                Write($"BoundKind.{StripBound(node.Name)}, syntax");
                WriteArgumentsToMethod(", ", AllSpecifiableFields(BaseType(node)), node, "");
            }
            void WriteBaseCall_ForKindSyntaxFields()
            {
                // Base call has kind, syntax, fields
                Write("kind, syntax");
                WriteArgumentsToMethod(", ", AllSpecifiableFields(BaseType(node)), node, "");
            }
        }
        IEnumerable<string> OutputFirstParameters(bool isPublic)
        {
            if (!isPublic) yield return NameAsType("kind", "BoundKind");
            yield return NameAsType("syntax", "SyntaxNode");
        }

        protected override void WriteAccept(string name)
        {
            F("Public Overrides", "Accept", Parameters(NameAsType("visitor", "BoundTreeVisitor")), boundNode);
            Return($"visitor.Visit{StripBound(name)}(Me)");
            End_Function(thenBlankLine: false);
        }


        protected override void Write_Update(Node node, bool emitNew)
        {
            Blank();
            var modifier = emitNew ? " Shadows" : "";
            F($"Public{modifier}", "Update", AllSpecifiableFields(node).Select(field => NameAsType(field.Name, field.Type)).ToArray(), node.Name);

            if (!AllSpecifiableFields(node).Any())
            {
                Return("Me");
            }
            else
            {
                Write("If ");
                AndAlso(AllSpecifiableFields(node), field => $"({ToCamelCase(field.Name)} {WriteComparision(field)}");
                Write(" Then ");
                Return("Me");
                Declaration("result", node.Name, null, isNew: true);
                ParenList((new[] { "Me.Syntax" }).Concat(AllSpecifiableFields(node).Select(f => ToCamelCase(f.Name))).Concat(new[] { "Me.HasErrors" }));
                EOL();
                WriteLine("If Me.WasCompilerGenerated Then result.SetWasCompilerGenerated()");
                Return("result");
            }
            End_Function();
            // Helpers
            string WriteComparision(Field field) => IsValueType(field.Type) ? $"= Me.{field.Name})"
                                                                            : $"Is Me.{field.Name})";
        }

        protected override void WriteVisitor()
        {
            Write_VisitInternal();
            Write_Visit_AsR();
            Write_Vist_AsBoundNode();

            void Write_VisitInternal()
            {
                Friend_MustInherit_Partial_Class($"BoundTreeVisitor(Of A,R)");
                Blank();

                WriteLine("<MethodImpl(MethodImplOptions.NoInlining)>");
                WriteLine($"Friend Function VisitInternal({NodeAsBoundNode()}, {NameAsType("arg", "A")}) As R", thenIndent: true);
                SelectCase();
                Return("DefaultVisit(node, arg)");
                End_Function();
                End_Class();
            }
            void SelectCase()
            {
                WriteLine("Select Case node.Kind", thenIndent: true);
                var _OfTypes = _tree.Types.OfType<Node>().ToList();
                var widest = _OfTypes.Max(node => FixKeyword(StripBound(node.Name)).Length);
                for (var idx = 0; idx < _OfTypes.Count; idx++)
                {
                    var node = _OfTypes[idx];
                    var stripName = StripBound(node.Name);
                    var name = FixKeyword(stripName);
                    WriteLine($"Case BoundKind.{name}{new string(' ', widest - name.Length)}: Return Visit{stripName}(CType(node, {node.Name}), arg)");
                }
                End_Select();
            }
            void Write_Visit_AsR()
            {
                Friend_MustInherit_Partial_Class("BoundTreeVisitor(Of A,R)");
                Blank();
                foreach (var node in _tree.Types.OfType<Node>())
                    WriteVisitor(node, Parameters(NodeAs(node), NameAsType("arg", "A")), "R", "node,arg");
                End_Class();
            }
            void Write_Vist_AsBoundNode()
            {
                Friend_MustInherit_Partial_Class("BoundTreeVisitor");
                Blank();
                foreach (var node in _tree.Types.OfType<Node>())
                    WriteVisitor(node, Parameters(NodeAs(node)), boundNode, "node");
                End_Class();
            }

            void WriteVisitor(Node node, string[] parameters, string returns, string argument)
            {
                F("Public Overridable", $"Visit{StripBound(node.Name)}", parameters.ToArray(), returns);
                Return($"Me.DefaultVisit({argument})");
                End_Function();
            }
        }
        private string[] Parameters(params string[] parameters) => parameters;

        private string NodeAsBoundNode() => NameAsType("node", "BoundNode");
        private string NodeAs(Node node) => NameAsType("node", node.Name);

        private string Visit(Node node) => $"Visit{StripBound(node.Name)}";

        private const string boundNode = "BoundNode";
        protected override void WriteWalker()
        {
            Friend_MustInherit_Partial_Class("BoundTreeWalker","BoundTreeVisitor");
            foreach (var node in _tree.Types.OfType<Node>())
            {
                F("Public Overrides", Visit(node), Parameters(NodeAs(node)).ToArray(), boundNode);
                Visiting(node);
                Return("Nothing");
                End_Function();
            }
            End_Class();

            void Visiting(Node node)
            {
                foreach (var field in AllFields(node).Where(f => IsDerivedOrListOfDerived(boundNode, f.Type) && !SkipInVisitor(f)))
                {
                    var member = IsNodeList(field.Type) ? "List" : "";
                    WriteLine($"Me.Visit{member}(node.{field.Name})");
                }
            }
        }
        void ReturnType(string type) => WriteLine($" As {type}",thenIndent: true);
#region "Function Writing"
        private void F(string modifier,string name,string[] parameters, string returns, bool thenIndent = true)
        {
            if (modifier != null) Write($"{modifier} ");
            Write($"Function {name}");
            WriteParameters(parameters);
            ReturnType(returns);
        }
        private void WriteParameters(string[] parameters)
        {
            ParenList(parameters, x => x);

            //var isFirst = true;
            //foreach(var parameter in parameters)
            //{
            //    if (!isFirst) { WriteComma(); }
            //    isFirst = false;
            //    Write(parameter);
            //}
            //void WriteComma() => Write(", ");
        }

        private string VAR(string name) => ToCamelCase(StripBound(name));
        #endregion
        protected override void WriteTreeDumperNodeProducer()
        {
            Write_Class("Friend NotInheritable ", "BoundTreeDumperNodeProducer", "BoundTreeVisitor(Of Object, TreeDumperNode)");
//            WriteLine("Friend NotInheritable Class BoundTreeDumperNodeProducer : Inherits BoundTreeVisitor(Of Object, TreeDumperNode)", thenIndent: true);
            WriteLine("Private Sub New()", afterBlankLine: true);
            WriteLine("End Sub", thenBlankLine: true);
            Write_MakeTree();
            foreach (var node in _tree.Types.OfType<Node>())
            {
                F("Public Overrides", Visit(node), Parameters(NodeAs(node),NameAsType("arg", "Object")).ToArray(),"TreeDumperNode");
                Write($"Return New TreeDumperNode(\"{VAR(node.Name)}\", Nothing, ");
                var allFields = AllFields(node).ToArray();
                if (allFields.Length > 0)
                {
                    // Write("New TreeDumperNode() ");
                    WriteLine("{", thenIndent: true);
                    for (var i = 0; i < allFields.Length; ++i)
                    {
                        var field = allFields[i];
                        Write($"New TreeDumperNode(\"{_Field(field)}\", ");
                        if (IsDerivedType(boundNode, field.Type))
                            Write($"Nothing, {{ Visit(node.{field.Name}, Nothing) }})");
                        else if (IsListOfDerived(boundNode, field.Type))
                            Write($"Nothing, From x In node.{field.Name} Select Visit(x, Nothing))");
                        else
                            Write($"node.{field.Name}, Nothing)");

                        if (i == allFields.Length - 1)
                            WriteLine("");
                        else
                            WriteLine(",");
                    }
                    WriteLine("})", undent: true);
                }
                else
                {
                    WriteLine("Array.Empty(Of TreeDumperNode)())");
                }
                End_Function();
            }
            End_Class();


            void Write_MakeTree()
            {
                F("Public Shared","MakeTree", Parameters(NodeAsBoundNode()), "TreeDumperNode" );
                Return("(New BoundTreeDumperNodeProducer()).Visit(node, Nothing)");
                End_Function();
            }

        }

        string _Field(Field field) => ToCamelCase(field.Name);

        private string NameAsType(string name, string typename) => $"{ToCamelCase(name)} As {typename}";

        protected override void WriteRewriter()
        {
            Friend_MustInherit_Partial_Class("BoundTreeRewriter", "BoundTreeVisitor");
            
            foreach (var node in _tree.Types.OfType<Node>())
                WriteFunction(node);
            End_Class();

            void WriteFunction(Node node)
            {
                F("Public Overrides", Visit(node),Parameters( NodeAs(node)), "BoundNode");
                var hadField = false;
                foreach (var field in AllNodeOrNodeListFields(node))
                {
                    hadField = true;
                    Declaration(field.Name,field.Type,"",false);
                    if (SkipInVisitor(field))
                        WriteLine($"node.{field.Name}");
                    else if (IsNodeList(field.Type))
                        WriteLine($"Me.VisitList(node.{field.Name})");
                    else
                        WriteLine($"DirectCast(Me.Visit(node.{field.Name}), {field.Type})");
                }
                foreach (var field in AllTypeFields(node))
                {
                    hadField = true;
                    Declaration(field.Name, "TypeSymbol",$"Me.VisitType(node.{field.Name})",false,true);
                }
                ReturnNode();
                if (hadField)
                {
                    Write(".Update");
                    ParenList(AllSpecifiableFields(node), field => IsDerivedOrListOfDerived("BoundNode", field.Type) || field.Type == "TypeSymbol" ? ToCamelCase(field.Name) : $"node.{field.Name}");
                }
                EOL();
                End_Function();
            }
        }
        private void Declaration(string field, string typeName, string value , bool isNew, bool eol = false)
        {
            Write($"Dim {NameAsType(field, IsAsNew())}");
            if (value != null) Write($" = {value}");
            if (eol) EOL();
            string IsAsNew() => (isNew ? "New " : "") + typeName;
        }

        protected override bool   IsImmutableArray(string typeName) => typeName.StartsWith("ImmutableArray(Of", StringComparison.OrdinalIgnoreCase);
        protected override bool   IsNodeList(string typeName) => typeName.StartsWith("IList(Of", StringComparison.OrdinalIgnoreCase) ||
                                                               typeName.StartsWith("ImmutableArray(Of", StringComparison.OrdinalIgnoreCase);
        protected override bool   IsKeyword(string name) => Keywords.Contains(name.ToLower());
        protected override string GetGenericType(string typeName)
        {
            var iStart = typeName.IndexOf("(Of", StringComparison.OrdinalIgnoreCase);
            return (iStart == -1) ? typeName : typeName.Substring(0, iStart);
        }
        protected override string GetElementType(string typeName)
        {
            var iStart = typeName.IndexOf("(Of", StringComparison.OrdinalIgnoreCase);
            if (iStart == -1) return string.Empty;
            var iEnd = typeName.IndexOf(')', iStart + 3);
            if (iEnd < iStart) return string.Empty;
            return typeName.Substring(iStart + 3, iEnd - iStart - 3).Trim();
        }
        protected override string EscapeKeyword(string name) => "[" + name + "]";
        #endregion

        private static HashSet<string> Keywords = new HashSet<string>(new string[]
        {  "addhandler", "addressof", "alias", "and", "andalso", "as",
           "boolean", "byref", "byte", "byval",
            "call", "case", "catch", "cbool", "cbyte", "cchar", "cdate", "cdbl", "cdec", "char", "cint", "class", "clng", "cobj", "const", "continue",
            "csbyte", "cshort", "csng", "cstr", "ctype", "cuint", "culng", "cushort",
            "date", "decimal", "declare", "default", "delegate", "dim", "directcast", "do", "double",
            "each", "else", "elseif", "end", "endif", "enum", "erase", "error", "event", "exit",
            "false", "finally", "for", "friend", "function",
            "get", "gettype", "getxmlnamespace", "global", "gosub", "goTo",
            "handles",
            "if", "implements", "imports", "in", "inherits", "integer", "interface", "is", "isnot",
            "let", "lib", "like", "long", "loop",
            "me", "mod", "module", "mustinherit", "mustoverride", "mybase", "myclass",
            "namespace", "narrowing", "new", "next", "not", "nothing", "notinheritable", "notoverridable",
            "object", "of", "on", "operator", "option", "optional", "or", "orelse", "overloads", "overridable", "overrides",
            "paramArray", "partial", "private", "property", "protected", "public",
            "raiseevent", "readonly", "redim", "rem", "removehandler", "resume", "return",
            "sbyte", "select", "set", "shadows", "shared", "short", "single", "static", "step", "stop", "string", "structure", "sub", "synclock",
            "then", "throw", "to", "true", "try", "trycast", "typeof",
            "uinteger", "ulong", "ushort", "using",
            "variant", "wend", "when", "while", "widening", "with", "withevents", "writeonly",
            "xor"}
        );
    }
}
